languageCode = "en-en"
title = "ArtCommissions-SabrinaFrank -Portfolio-"
baseurl = "https://www.ArtCommissions-SabrinaFrank.de/"
theme = ""

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

[params]
  name = "Sabrina Frank"
  description = "Graphite & Paper"
  copyright = "Creative Commons Licence | Hugo Theme: Prologue | Edited by: Sabrina Frank"


[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/ArtCommissionsSabrinaFrank/?ref=py_c"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/SabiFrank"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:sabrina.frank.95@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Mark Tremonti"
  alt = "Portrait depicting the guitarist Mark Tremonti (Alter Bridge)"
  source = "img/01.jpg"
  url = ""

[[params.portfolio1]]
  title = "Iron Man"
  alt = "Portrait depicting the actor Robert Downey Jr. as Iron Man"
  source = "img/02.jpg"
  url = ""
  
[[params.portfolio1]]
  title = "Finnick Odair"
  alt = "Portrait depicting the actor Sam Claflin as Finnick Odair (Hunger Games)"
  source = "img/04.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Sherlock Holmes"
  alt = "Portrait depicting the actor Benedict Cumberbatch as Sherlock Holmes"
  source = "img/05.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Family portrait 1"
  alt = "Family portrait 1"
  source = "img/06.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Dogs"
  alt = "Dogs"
  source = "img/07.jpg"
  url = "#"
  
 [[params.portfolio1]]
  title = "Portrait 1"
  alt = "Portrait 1"
  source = "img/08.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Portrait 2"
  alt = "Portrait 2"
  source = "img/09.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Portrait 3"
  alt = "Portrait 3"
  source = "img/010.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Portrait 4"
  alt = "Portrait 4"
  source = "img/011.jpg"
  url = "#"
  
[[params.portfolio1]]
  title = "Portrait 5"
  alt = "Portrait 5"
  source = "img/012.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Forest Spirit 1"
  alt = "Forest Spirit 1"
  source = "img/10.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Forest Spirit 2"
  alt = "Forest Spirit 2"
  source = "img/11.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Forest Spirit 3"
  alt = "Forest Spirit 3"
  source = "img/12.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Water & Wind"
  alt = "Water & Wind"
  source = "img/13.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Mermaid"
  alt = "Mermaid"
  source = "img/14.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Hunter"
  alt = "Hunter"
  source = "img/15.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Anatomy"
  alt = "Anatomy"
  source = "img/16.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Decay"
  alt = "Decay"
  source = "img/18.jpg"
  url = "#"
  
[[params.portfolio2]]
  title = "Dreaming"
  alt = "Dreaming"
  source = "img/19.jpg"
  url = "#"
  
# Portfolio column 3
 
[[params.portfolio3]]
  title = "Doubt"
  alt = "Doubt"
  source = "img/111.jpg"
  url = "#"
  
[[params.portfolio3]]
  title = "Thinking"
  alt = "Thinking"
  source = "img/112.jpg"
  url = "#"
  
[[params.portfolio3]]
  title = "Tough"
  alt = "Tough"
  source = "img/113.jpg"
  url = "#"
  
[[params.portfolio3]]
  title = "Blinded"
  alt = "Blinded"
  source = "img/114.jpg"
  url = "#"
  
[[params.portfolio3]]
  title = "Mage"
  alt = "Mage"
  source = "img/115.jpg"
  url = "#"
 
 [[params.portfolio3]]
  title = "Spring"
  alt = "Spring"
  source = "img/116.jpg"
  url = "#"
  
 [[params.portfolio3]]
  title = "Summer"
  alt = "Summer"
  source = "img/117.jpg"
  url = "#"
  
 [[params.portfolio3]]
  title = "Autumn"
  alt = "Autumn"
  source = "img/118.jpg"
  url = "#"
  
 [[params.portfolio3]]
  title = "Winter"
  alt = "Winter"
  source = "img/119.jpg"
  url = "#"
 
